## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('aodv',
                                 ['wifi', 'internet', 'aodv', 'internet-apps'])
    obj.source = 'aodv.cc'
    
    obj = bld.create_ns3_program('aodv-lrpwan',
                                 ['wifi', 'internet', 'aodv', 'internet-apps', 'lr-wpan', 'sixlowpan', 'netanim'])
    obj.source = 'aodv-lrwpan.cc'
