## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('ConstantPosition_Model', ['network', 'sixlowpan', 'internet', 'lr-wpan', 'internet-apps', 'netanim', 'mpl', 'topology-read' , 'statistics'])
    obj.source = 'ConstantPosition_Model.cc'
