# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('mpl', ['internet', 'core'])
    module.source = [
        'model/mpl.cc',
        'model/seed-set-entry.cc',
        'model/mpl-data-message.cc',
        'helper/mpl-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('mpl')
    module_test.source = [
        'test/mpl-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/mpl-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'mpl'
    headers.source = [
        'model/mpl.h',
        'model/seed-set-entry.h',
        'model/mpl-data-message.h',
        'helper/mpl-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

